services:

  postgres: #postgres is a service
    image: postgres:17
    
    container_name: wallet-postgres

    #db settings
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wallet
    
    ports:
      - "5433:5432"
    
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data:
  